export const initialBoard: BoardSquare[][] = [
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
  [
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
    { isRevealed: false, value: 0 },
  ],
];
