export const initialBoard: BoardSquare[][] = [
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
  [
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
    { isRevealed: false, isFlagged: false, value: 0, surroundingFlagCount: 0 },
  ],
];

export const BOMB_VALUE = -1;
